import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const canonicalContent=new URL('./content/library-v2.json',import.meta.url);const content=JSON.parse(fs.readFileSync(fs.existsSync(canonicalContent)?canonicalContent:new URL('./library-v2.json',import.meta.url),'utf8')); let code=fs.readFileSync(new URL('./library.js',import.meta.url),'utf8');
code=code.replace('render();\n})();','window.TEST={render,matches,validateContent,validateBook,blank,books,saveBooks,filtered,verifyEditor,editor,topicPage,chrome,validateStudy,saveStudy,bindStudy,ris,rememberSection,prepareDraft,studyPage,readingCard,comparisonSamples,corpusLab,transferNotebook,argumentTrace,argumentText,usedEvidence,synthesisLab,synthesisText,synthesisTrace,transferSynthesis,bindSynthesis,hasSynthesis,liveSamples,getSample,samplesFor,samplePage,matchingSamples,bindSamples,sampleAnalysisText,validateSamples,validateProtocol,coverageContents,setSampleFilters:v=>sampleFilters=v,getEditorDraft:()=>editorDraft,getStudy:()=>study,setSearch:v=>searchState=v,setEditorTab:v=>editorTab=v};render();\n})();');
class El{constructor(id){this.id=id;this.value='';this.dataset={};this.attrs={};this._html='';this.textContent='';}set innerHTML(v){this._html=v;}get innerHTML(){return this._html;}setAttribute(k,v){this.attrs[k]=v;}querySelectorAll(sel){if(sel==='a.card')return [...this._html.matchAll(/<a class="card" href="([^"]+)"/g)].map(m=>({href:m[1]}));return [];}addEventListener(event,handler){this.events=this.events||{};this.events[event]=handler;}focus(){}scrollIntoView(){}click(){}}
const nodes={};for(const id of ['search-suggestions','global-search','view','language','brand','search-label','query','search-button','language-label','skip','nav','footer','main','crumb'])nodes[id]=new El(id);const dynamic=new Map();
const doc={documentElement:{lang:'es'},title:'',getElementById(id){if(nodes[id])return nodes[id];if(nodes.view.innerHTML.includes('id="'+id+'"')){if(!dynamic.has(id))dynamic.set(id,new El(id));return dynamic.get(id);}return null;},createElement(){return new El('generated');}};
const storage=new Map();const listeners={};const win={addEventListener:(k,f)=>listeners[k]=f,scrollTo(){},print(){}};const location={hash:'#inicio',href:'https://example.org/'};let writes=0;
const context={console,document:doc,window:win,location,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},fetch:async(u,o)=>{if(String(u).startsWith('https://api.github.com')){if(o?.method==='PUT')writes++;return {ok:false,status:403,json:async()=>({message:'Denied'})};}return {ok:true,json:async()=>structuredClone(content)};},structuredClone,URL,URLSearchParams,Intl,Date,Blob,TextEncoder,btoa:s=>Buffer.from(s,'binary').toString('base64'),setTimeout,confirm:()=>true};
vm.createContext(context);vm.runInContext(code,context);await new Promise(r=>setTimeout(r,5));const t=win.TEST;assert(t);assert.equal(content.topics.length,20);assert.equal(content.topics.slice(0,16).filter(x=>x.category===x.slug).length,16);t.validateContent(content);
for(const lang of ['es','nl']){nodes.language.value=lang;nodes.language.onchange({target:nodes.language});for(const route of ['inicio','bok','indice','comparar','fuentes','estudio','corpus',...content.references.map(x=>'lectura/'+x.id),...content.topics.map(x=>'tema/'+x.slug),...['1','2','3'].flatMap(k=>[0,1,2,3,4,5].map(i=>'cuaderno/'+k+'/'+i)),...['topics','ui','refs','guide'].map(()=> 'admin')]){location.hash='#'+route;t.render(false);assert(!nodes.view.innerHTML.includes('[object Object]'),route);assert(!nodes.view.innerHTML.includes('undefined'),route);assert(nodes.view.innerHTML.length>0);}}
assert(t.matches(content.topics.find(x=>x.slug==='se'),'se'));assert(t.matches(content.topics.find(x=>x.slug==='modo'),'subjuntivo'));assert(t.matches(content.topics.find(x=>x.slug==='adquisicion'),'interlanguage'));
const draft=t.blank();draft.fields.title='Borrador anterior';assert.equal(t.validateBook(draft).fields.title,'Borrador anterior');t.books[1].fields.title='Conservar';location.hash='#cuaderno/1/0';t.render(false);t.saveBooks(1);assert.equal(JSON.parse(storage.get('fontys-spaans-cuaderno-v1')).books[1].fields.title,'Conservar');
const malicious=structuredClone(content.topics[0]);malicious.theory.es='<img src=x onerror=alert(1)>';nodes.language.value='es';nodes.language.onchange({target:nodes.language});assert(!t.topicPage(malicious).includes('<img src=x'));const bad=structuredClone(content);bad.references[0].url='javascript:alert(1)';assert.throws(()=>t.validateContent(bad));const broken=structuredClone(content);broken.topics[0].related.push({slug:'missing',reason:{es:'a',nl:'b'}});assert.throws(()=>t.validateContent(broken));location.hash='#admin';t.render(false);doc.getElementById('editor-token').value='invalid-test-credential';await assert.rejects(t.verifyEditor());assert.equal(writes,0);assert.equal(storage.has('editorToken'),false);
console.log('PASS: 2 languages, 20 thematic routes, 18 notebook steps, catalogue/index/sources, draft schema and saving, XSS escaping, invalid URLs/relations rejected, unauthorized publishing blocked.');

for(const tab of ['topics','ui','refs','guide','glossary','search','work']){t.setEditorTab(tab);t.editor();assert(!nodes.view.innerHTML.includes('undefined'),tab);}
t.setSearch({q:'multilinguismo',scope:'',domain:'',depth:''});assert(t.matches(content.topics.find(x=>x.slug==='repertorios'),'multilinguismo'));
assert(t.matches(content.topics.find(x=>x.slug==='norma'),'taalpluralisme'));assert(t.matches(content.topics.find(x=>x.slug==='pluricentrico'),'pluricentrisch Spaans'));
t.setSearch({q:'verbo en singular o plural',scope:'terms',domain:'',depth:''});assert(t.matches(content.topics.find(x=>x.slug==='congruencia'),'verbo en singular o plural'));
t.setSearch({q:'Ellis',scope:'sources',domain:'',depth:''});assert(t.matches(content.topics.find(x=>x.references.includes('ellis')),'Ellis'));t.setSearch({q:'',scope:'',domain:'',depth:''});
for(const r of content.references){const exported=t.ris(r);assert(exported.startsWith('TY  - '));assert(exported.includes('N1  - '+r.apa));assert(exported.includes('UR  - '+new URL(r.url).href));}
assert(t.ris(content.references.find(x=>x.id==='ellis')).includes('DO  - 10.5070/L2.V1I1.9054'));
location.hash='#tema/repertorios';t.render(false);const fav=new El('favorite');fav.dataset={saveKind:'topic',saveId:'repertorios'};const originalQuery=nodes.view.querySelectorAll;nodes.view.querySelectorAll=sel=>sel==='[data-save-kind]'?[fav]:[];t.bindStudy();fav.onclick();assert(t.getStudy().items.some(x=>x.id==='repertorios'));assert(JSON.parse(storage.get('bcl-study-tools-v1')).items.some(x=>x.id==='repertorios'));fav.onclick();assert(!t.getStudy().items.some(x=>x.id==='repertorios'));
location.hash='#lectura/ans';t.render(false);const note=new El('source-note');note.dataset={sourceId:'ans',sourceNote:'sourceLimits'};note.value='Mi análisis con una limitación';nodes.view.querySelectorAll=sel=>sel==='[data-source-note]'?[note]:[];t.bindStudy();note.oninput();assert.equal(t.getStudy().sourceNotes.ans.sourceLimits,note.value);nodes.view.querySelectorAll=originalQuery;
t.rememberSection('repertorios','case');assert(t.studyPage().includes('tema/repertorios?section=case'));const studyBackup=t.validateStudy(JSON.parse(JSON.stringify(t.getStudy())));assert.equal(studyBackup.sourceNotes.ans.sourceLimits,note.value);const corrupt=JSON.parse(JSON.stringify(studyBackup));corrupt.items=[{kind:'bad',id:'ans',list:'study'}];assert.throws(()=>t.validateStudy(corrupt));
const oldDraft=structuredClone(content);delete oldDraft.popularTopics;delete oldDraft.searchAliases;delete oldDraft.ui.myStudy;delete oldDraft.references[0].readingFocus;const migrated=t.prepareDraft(oldDraft);t.validateContent(migrated);assert(migrated.ui.myStudy.nl);assert.equal(migrated.topics[0].theory.es,oldDraft.topics[0].theory.es);
location.hash='#bok';t.render(false);assert(nodes.view.innerHTML.includes('taalpluralisme')||nodes.view.innerHTML.includes('pluralismo'));assert(nodes.view.innerHTML.includes('clear-search'));assert(nodes.view.innerHTML.includes('search-scope'));
assert(nodes['search-suggestions'].innerHTML.includes('multilingüismo'));assert(nodes['search-suggestions'].innerHTML.includes('meertaligheid'));
console.log('PASS: bilingual suggestions and aliases, scoped search, all source fiches, corpus route, 7 editor tabs, favorite toggle and persistence, reading notes, reading position, study backup validation, older editor draft migration, APA/RIS/DOI output.');

for(const lang of ['es','nl']){nodes.language.value=lang;nodes.language.onchange({target:nodes.language});for(const unit of content.topics){const html=t.topicPage(unit);for(const key of ['critical','enquiry','progress','strategic'])assert(html.includes('id="section-'+key+'"'));assert(html.includes(unit.study.deepTheory[lang].split('\n')[0].slice(0,70).replaceAll('&','&amp;').replaceAll('\"','&quot;')));assert(unit.study.caseData.length>=4);assert.equal(unit.study.analyses.length,3);assert(unit.study.criticalQuestions[lang].split('\n').length>=4);}}
location.hash='#tema/norma';t.render(false);const response=new El('response');response.dataset={topicWork:'analysisResponse',topicId:'norma'};response.value='Mi interpretación con evidencia';nodes.view.querySelectorAll=sel=>sel==='[data-topic-work]'?[response]:[];t.bindStudy();response.oninput();assert.equal(t.getStudy().topicWork.norma.analysisResponse,response.value);const previous=t.books[2].fields.interpretation='Contenido anterior';assert(t.transferNotebook('norma',2));assert(t.books[2].fields.interpretation.startsWith(previous));assert(t.books[2].fields.interpretation.includes(response.value));const once=t.books[2].fields.interpretation;t.transferNotebook('norma',2);assert.equal(t.books[2].fields.interpretation,once);assert.equal(t.books[1].fields.title,'Conservar');nodes.view.querySelectorAll=originalQuery;
const older=structuredClone(t.getStudy());delete older.topicWork;assert(t.validateStudy(older).topicWork);const invalidWork=structuredClone(t.getStudy());invalidWork.topicWork.norma.analysisResponse=123;assert.throws(()=>t.validateStudy(invalidWork));const oldEditorial=structuredClone(content);delete oldEditorial.topics[0].study;t.validateContent(t.prepareDraft(oldEditorial));const missingLayer=structuredClone(content);missingLayer.topics[0].study.criticalQuestions.nl='';assert.throws(()=>t.validateContent(missingLayer));
console.log('PASS: 20 bilingual critical layers, full cases and models, response persistence, legacy migration, additive notebook transfer and deduplication.');

const earlierStudy=structuredClone(content);delete earlierStudy.topics[0].study.strategicQuestions;t.validateContent(t.prepareDraft(earlierStudy));

const norma=content.topics.find(x=>x.slug==='norma');
for(const lang of ['es','nl']){nodes.language.value=lang;nodes.language.onchange({target:nodes.language});for(const unit of content.topics){const html=t.topicPage(unit);assert(html.includes('id="section-reasoning"'));assert(html.includes('data-topic-work="argumentSourceId"'));assert.equal((html.match(/data-topic-work="argument(?:Data|Claim|Warrant|Alternative|Options|Decision|Transfer|Revision)"/g)||[]).length,8);}}
const work=t.getStudy().topicWork.norma;assert.equal(t.argumentTrace(norma).missing.length,8);const sourceId=norma.references.at(-1);work.argumentSourceId=sourceId;assert.equal(t.usedEvidence(norma),null);const book3Framework=t.books[3].fields.framework;t.transferNotebook('norma',3);assert.equal(t.books[3].fields.framework,book3Framework);
for(const key of ['argumentData','argumentClaim','argumentWarrant','argumentAlternative','argumentOptions','argumentDecision','argumentTransfer','argumentRevision'])work[key]='Razonamiento documentado: '+key;
assert.equal(t.argumentTrace(norma).missing.length,0);assert.equal(t.argumentTrace(norma).evidence,null);t.getStudy().sourceNotes[sourceId]={sourceClaim:'Afirmación delimitada',sourcePassage:'Apartado consultado',sourceConsultation:'Resumen editorial, no texto completo',sourceLimits:'Otra población y contexto'};assert.equal(t.usedEvidence(norma),sourceId);assert(t.argumentText(norma).includes('Otra población y contexto'));t.transferNotebook('norma',3);assert(t.books[3].fields.framework.includes(content.references.find(x=>x.id===sourceId).apa));assert(!t.books[3].fields.framework.includes(content.references.find(x=>x.id===norma.references[0]).apa));assert(t.books[3].fields.objective.includes(work.argumentOptions));assert(t.books[3].fields.nextsteps.includes(work.argumentRevision));
const argumentBackup=t.validateStudy(JSON.parse(JSON.stringify(t.getStudy())));assert.equal(argumentBackup.topicWork.norma.argumentSourceId,sourceId);assert.equal(argumentBackup.sourceNotes[sourceId].sourceConsultation,'Resumen editorial, no texto completo');work.argumentSourceId='unknown';assert.equal(t.usedEvidence(norma),null);work.argumentSourceId=sourceId;
assert.equal(content.references.filter(x=>x.enrichment).length,17);assert(content.references.filter(x=>x.enrichment).every(x=>x.apa&&x.scope.es&&x.scope.nl&&x.verificationUrl&&x.checked==='2026-10-09'));
console.log('PASS: 20 bilingual reasoning workshops, 8 argument steps, missing-step detection, explicit source consultation, evidence boundaries, selected-source-only notebook transfer, argument export and backup preservation, 17 verified enriched references.');

for(const lang of ['es','nl']){nodes.language.value=lang;nodes.language.onchange({target:nodes.language});for(const unit of content.topics){const html=t.topicPage(unit);assert(html.includes('id="section-synthesis"'));assert(html.includes(content.ui.synthesisTitle[lang]));assert(html.includes(content.ui.synthesisHonesty[lang]));assert.equal((html.match(/data-synthesis-choice="true"/g)||[]).length,6);}}
const sw=t.getStudy().topicWork.norma;assert(!t.hasSynthesis(norma));sw.synthesisQuestion='¿Qué permite afirmar este estudio?';sw.synthesisHypothesis='Hipótesis provisional';sw.synDialogue='Comparación sin confundir poblaciones';sw.synDecision='Elegir ejemplos contextualizados';sw.synCheck='Contrastar una producción nueva';sw.synthesisSlot1Id=norma.references[0];sw.synthesisSlot2Id=norma.references.at(-1);assert.equal(t.synthesisTrace(norma).distinct,2);assert.equal(t.synthesisTrace(norma).incomplete.length,2);
const fields=['synClaim','synPassage','synConsultation','synEvidence','synMethod','synLimits'];for(const key of fields)sw['synthesisSlot1'+key]='Nota documentada '+key;sw.synthesisSlot1Role='synQualifies';assert.equal(t.synthesisTrace(norma).documented.length,1);assert(t.synthesisText(norma).includes('Nota documentada synMethod'));assert(t.synthesisText(norma).includes('Hipótesis provisional'));assert(!t.synthesisText(norma).includes('\\n'));const oldFramework=t.books[1].fields.framework;assert(t.transferSynthesis(norma,1));assert(t.books[1].fields.framework.startsWith(oldFramework));assert(t.books[1].fields.framework.includes(content.references.find(r=>r.id===sw.synthesisSlot1Id).apa));assert(!t.books[1].fields.framework.includes(content.references.find(r=>r.id===sw.synthesisSlot2Id).apa));assert(t.books[1].fields.objective.includes(sw.synDecision));const onceSynthesis=t.books[1].fields.framework;t.transferSynthesis(norma,1);assert.equal(t.books[1].fields.framework,onceSynthesis);
sw.synthesisSlot2Id=sw.synthesisSlot1Id;assert.equal(t.synthesisTrace(norma).duplicates.length,1);const backupSynth=t.validateStudy(JSON.parse(JSON.stringify(t.getStudy())));assert.equal(backupSynth.topicWork.norma.synthesisSlot1synConsultation,sw.synthesisSlot1synConsultation);const escapingSynth=sw.synDialogue='<img src=x onerror=alert(1)>';assert(!t.synthesisLab(norma).includes('<img src=x'));sw.synDialogue='Comparación documentada';
location.hash='#tema/norma';t.render(false);const changing=new El('changing');changing.dataset={topicId:'norma',topicWork:'synthesisSlot1Id',synthesisChoice:'true'};changing.value=norma.references.at(-1);nodes.view.querySelectorAll=sel=>sel==='[data-synthesis-choice]'?[changing]:[];t.bindSynthesis();changing.onchange();assert.equal(sw.synthesisSlot1Id,changing.value);assert.equal(sw.synthesisSlot1synClaim,undefined);assert.equal(sw.synthesisSlot1Role,undefined);nodes.view.querySelectorAll=originalQuery;
assert.equal(t.books[1].fields.title,'Conservar');console.log('PASS: 20 bilingual optional synthesis routes, 6 source slots, support/challenge/qualification/alternative/uncertainty roles, source completeness, duplicates, export, backup, notebook additive transfer, source replacement and escaping.');

assert(content.references.every(r=>r.apa.includes('https://')));for(const lang of ['es','nl']){nodes.language.value=lang;nodes.language.onchange({target:nodes.language});const html=t.corpusLab();for(const field of ['resourceVersion','searchScope','sampleSelection','sampleProvenance','sampleStatus','counterexamples','comparisonLimits'])assert(html.includes('data-corpus-note="'+field+'"'));assert(html.includes(content.ui.corpusProvenanceHelp[lang]));}
const badAuthentic=structuredClone(content);badAuthentic.samples[0].source='missing';assert.throws(()=>t.validateContent(badAuthentic));const orphanReading=structuredClone(content);orphanReading.topics[0].study.sourceReadings[0].id=content.references.find(r=>!orphanReading.topics[0].references.includes(r.id)).id;assert.throws(()=>t.validateContent(orphanReading));
location.hash='#corpus';t.render(false);const provenance=new El('provenance');provenance.dataset={corpusNote:'sampleProvenance'};provenance.value='Fuente original, fecha y localizador';nodes.view.querySelectorAll=sel=>sel==='[data-corpus-note]'?[provenance]:[];t.bindStudy();provenance.oninput();assert.equal(t.validateStudy(JSON.parse(JSON.stringify(t.getStudy()))).corpusNotes.general.sampleProvenance,provenance.value);nodes.view.querySelectorAll=originalQuery;
console.log('PASS: canonical content path preferred, 77 APA URLs, bilingual corpus provenance fields, preservation of notes, authentic-source linkage and directed-reading consistency.');

assert.equal(content.samples.length,46);assert.equal(new Set(content.samples.map(s=>s.genre)).size,10);assert.equal(content.references.filter(r=>r.sampleSource).length,39);
for(const lang of ['es','nl']){nodes.language.value=lang;nodes.language.onchange({target:nodes.language});location.hash='#muestras';t.render(false);assert(nodes.view.innerHTML.includes(content.ui.samplesIntro[lang]));for(const sample of content.samples){location.hash='#muestra/'+sample.id;t.render(false);const html=nodes.view.innerHTML;assert(html.includes('lang="'+sample.language+'"'));assert(html.includes(sample.text.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll("'",'&#39;')));assert(html.includes(content.ui.sampleStrategyText[lang].slice(0,40)));assert(html.includes('id="sample-note"'));assert(!html.includes('undefined'));}for(const unit of content.topics){assert(t.samplesFor(unit.slug).length>0);assert(t.topicPage(unit).includes('id="section-samples"'));}}
t.setSampleFilters({q:'',genre:'',language:'nl',topic:''});assert.equal(t.matchingSamples().length,6);t.setSampleFilters({q:'',genre:'conversacion',language:'',topic:''});assert.equal(t.matchingSamples().length,5);t.setSampleFilters({q:'',genre:'',language:'',topic:'se'});assert.equal(t.matchingSamples().length,8);t.setSampleFilters({q:'breinrot',genre:'',language:'',topic:''});assert.equal(t.matchingSamples().length,1);t.setSampleFilters({q:'',genre:'',language:'',topic:''});
t.setSearch({q:'breinrot',scope:'examples',domain:'',depth:''});assert(t.matches(content.topics.find(x=>x.slug==='repertorios'),'breinrot'));t.setSearch({q:'',scope:'',domain:'',depth:''});
for(const mutation of [d=>d.samples[0].id=d.samples[1].id,d=>d.samples[0].source='missing',d=>d.samples[0].locator.nl='',d=>d.samples[0].questions.es='',d=>d.samples[0].connections[0].topic='missing',d=>d.samples[0].comparison='missing',d=>d.samples[0].connections[0].reason.nl='',d=>d.samples[0].source='dato-coca'&& (d.references.find(r=>r.id==='dato-coca').status='pending')]){const d=structuredClone(content);mutation(d);assert.throws(()=>t.validateContent(d));}
const legacySamples=structuredClone(content);delete legacySamples.samples;assert.equal(t.prepareDraft(legacySamples).samples.length,46);const draftHidden=structuredClone(content);draftHidden.samples[0].status='hidden';draftHidden.samples[0].text='';draftHidden.samples[0].source='';assert(t.validateContent(draftHidden));
t.setEditorTab('samples');t.editor();assert(nodes.view.innerHTML.includes('new-sample'));assert(nodes.view.innerHTML.includes('data-sample-reason'));assert(nodes.view.innerHTML.includes('data-sample-simple="source"'));assert(nodes.view.innerHTML.includes('data-edit="questions"'));const before=t.getEditorDraft().samples.length;doc.getElementById('new-sample').events.click();assert.equal(t.getEditorDraft().samples.length,before+1);assert.equal(t.getEditorDraft().samples.at(-1).status,'hidden');assert(t.validateContent(t.getEditorDraft()));
location.hash='#muestra/valesco-traelo';t.render(false);const sampleNote=doc.getElementById('sample-note');sampleNote.dataset.sampleId='valesco-traelo';sampleNote.value='Localicé el turno y contrasté dos lecturas con límites.';sampleNote.addEventListener=(event,handler)=>sampleNote.handler=handler;t.bindSamples();sampleNote.handler({target:sampleNote});assert.equal(t.getStudy().corpusNotes['sample-valesco-traelo'].observations,sampleNote.value);assert(t.validateStudy(t.getStudy()).corpusNotes['sample-valesco-traelo']);assert(t.sampleAnalysisText(t.getSample('valesco-traelo')).includes('conversación 0019')||t.sampleAnalysisText(t.getSample('valesco-traelo')).includes('gesprek 0019'));assert(t.studyPage().includes('muestra/valesco-traelo'));
const badQuote=structuredClone(content.samples[0]);badQuote.text='<script>alert(1)</script>';assert(!t.samplePage(badQuote).includes('<script>alert'));
console.log('PASS: 46 authentic fiches, 10 genres, 6 Dutch samples, 20 topic links, bilingual sample pages and strategic questions, filters, global sample search, sample validation, legacy migration, editable bilingual sample CMS and hidden creation, persisted/exportable student analysis, backup and XSS protection.');

const actualOldDraft=structuredClone(content);delete actualOldDraft.samples;actualOldDraft.references=actualOldDraft.references.filter(r=>!r.sampleSource);for(const unit of actualOldDraft.topics)unit.references=unit.references.filter(id=>actualOldDraft.references.some(r=>r.id===id));const upgradedOldDraft=t.prepareDraft(actualOldDraft);assert(t.validateContent(upgradedOldDraft));assert.equal(upgradedOldDraft.references.length,77);assert.equal(upgradedOldDraft.topics[0].theory.es,actualOldDraft.topics[0].theory.es);
console.log('PASS: editorial drafts from before the sample bank migrate with preserved teacher text and repaired source/topic connections.');

for(const lang of ['es','nl']){nodes.language.value=lang;nodes.language.onchange({target:nodes.language});for(const example of content.samples){const html=t.samplePage(example);assert(html.includes(content.ui.sampleSocio[lang]));assert(html.includes(example.protocol.geolect[lang]));assert(html.includes(content.ui.samplePhenomenon[lang]));}for(const unit of content.topics){const html=t.coverageContents(unit.slug);for(const area of content.geoAreas)assert(html.includes(area.label[lang]));assert(html.includes(content.ui.samplePartial[lang]));}}
t.setSampleFilters({q:'',genre:'',language:'',topic:'',area:'mexico-centroamerica'});assert.equal(t.matchingSamples().length,7);t.setSampleFilters({q:'',genre:'',language:'',topic:'',area:'cono-sur'});assert.equal(t.matchingSamples().length,4);t.setSampleFilters({q:'',genre:'',language:'',topic:'',area:'caribe'});assert.equal(t.matchingSamples().length,5);t.setSampleFilters({q:'',genre:'',language:'',topic:'',area:''});
for(const mutate of [d=>d.samples[0].protocol.register.nl='',d=>d.samples[0].protocol.areas=['made-up'],d=>d.samples[0].protocol.levels=[],d=>d.samples.find(s=>s.language==='nl').protocol.areas=['caribe']]){const d=structuredClone(content);mutate(d);assert.throws(()=>t.validateContent(d));}
const beforeProtocol=structuredClone(content);delete beforeProtocol.geoAreas;beforeProtocol.samples.forEach(s=>delete s.protocol);t.validateContent(t.prepareDraft(beforeProtocol));
console.log('PASS: standardized bilingual phenomenon, level, geolect, country, locality, attribution evidence, register, norm and stigma fields; 5-area coverage with explicit gaps; regional filters; no country-based attribution; editorial migration and publication validation.');

assert.equal(content.samples.filter(s=>s.id.startsWith('cvc-')).length,20);
assert.equal(content.samples.filter(s=>s.media?.state==='playback').length,8);
assert(content.samples.filter(s=>s.media).every(s=>!s.media.listeningVerified&&!s.media.excerptVerified));
assert.equal(new Set(content.samples.filter(s=>s.protocol.areas.length).flatMap(s=>s.protocol.areas)).size,5);
for(const mutate of [d=>d.samples.find(s=>s.media).media.url='javascript:alert(1)',d=>d.samples.find(s=>s.media).media.fileUrl='http://example.org/a.mp4',d=>d.samples.find(s=>s.media).media.duration=-1,d=>d.samples.find(s=>s.media).media.listeningVerified=true,d=>d.samples.find(s=>s.media).media.excerptVerified=true]){const d=structuredClone(content);mutate(d);assert.throws(()=>t.validateContent(d));}
const oldOrigins=structuredClone(content);for(const s of oldOrigins.samples){delete s.protocol.speakerOrigin;delete s.protocol.publisherOrigin;delete s.media;}assert(t.validateContent(t.prepareDraft(oldOrigins)));
console.log('PASS: 20 new localized institutional transcripts; five regional areas; eight independently observed playback counters; no invented listening validation; unsafe media links and unsupported verification flags rejected; origin/media migration preserves draft text.');
